[build]
  command = "npm run build"
  publish = "build"

# Rewrite all React routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*" # Apply headers to all routes
  [headers.values]
    Access-Control-Allow-Origin = "https://selfdrive-looty.netlify.app"
    Access-Control-Allow-Credentials = "true" # Required if using cookies